import { WorkspacePageConfig } from './pages.model';

export const WORKSPACE_PAGES: WorkspacePageConfig[] = [
  {
    path: 'login',
    navLabel: 'Login',
    kind: 'login',
    eyebrow: 'Access',
    title: 'Login',
    primaryAction: { label: 'Open dashboard', path: '/dashboard' },
  },
  {
    path: 'dashboard',
    navLabel: 'Dashboard',
    kind: 'dashboard',
    eyebrow: 'Overview',
    title: 'Dashboard',
    primaryAction: { label: 'Review articles', path: '/articles' },
    secondaryAction: { label: 'Manage sites', path: '/settings/sites' },
  },
  {
    path: 'settings',
    navLabel: 'Settings',
    kind: 'settings',
    eyebrow: 'Administration',
    title: 'Settings',
    primaryAction: { label: 'Manage sites', path: '/settings/sites' },
  },
  {
    path: 'landing-page-editor',
    navLabel: 'Landing Page Editor',
    kind: 'landing-page-editor',
    eyebrow: 'Content design',
    title: 'Landing Page Editor',
    primaryAction: { label: 'Edit articles', path: '/articles' },
  },
  {
    path: 'articles',
    navLabel: 'Articles',
    kind: 'articles',
    eyebrow: 'Editorial',
    title: 'Articles',
    primaryAction: { label: 'Open editor', path: '/article-editor' },
  },
  {
    path: 'article-editor',
    navLabel: 'Article Editor',
    kind: 'article-editor',
    eyebrow: 'Writing',
    title: 'Article Editor',
    primaryAction: { label: 'Save draft', path: '/articles' },
  },
  {
    path: 'media-library',
    navLabel: 'Media Library',
    kind: 'media-library',
    eyebrow: 'Assets',
    title: 'Media Library',
    primaryAction: { label: 'Add media', path: '/media-library' },
  },
  {
    path: 'ai-assistant',
    navLabel: 'AI Assistant',
    kind: 'ai-assistant',
    eyebrow: 'Assistive writing',
    title: 'AI Assistant',
    primaryAction: { label: 'Open article editor', path: '/article-editor' },
  },
  {
    path: 'builds',
    navLabel: 'Builds',
    kind: 'builds',
    eyebrow: 'Delivery',
    title: 'Builds',
    primaryAction: { label: 'Trigger build', path: '/builds' },
  },
  {
    path: 'deployment-settings',
    navLabel: 'Deployment Settings',
    kind: 'deployment-settings',
    eyebrow: 'Publishing',
    title: 'Deployment Settings',
    primaryAction: { label: 'Open builds', path: '/builds' },
  },
];
