import { WorkspacePageConfig } from './pages.model';

export const WORKSPACE_PAGES: WorkspacePageConfig[] = [
  {
    path: 'login',
    navLabel: 'Login',
    kind: 'login',
    eyebrow: 'Access',
    title: 'Login',
    description: 'Sign in to manage the CMS, sites, articles, media, and builds.',
    primaryAction: { label: 'Open dashboard', path: '/dashboard' },
  },
  {
    path: 'dashboard',
    navLabel: 'Dashboard',
    kind: 'dashboard',
    eyebrow: 'Overview',
    title: 'Dashboard',
    description: 'A live operational view of the selected site and its publishing state.',
    primaryAction: { label: 'Review articles', path: '/articles' },
    secondaryAction: { label: 'Manage sites', path: '/sites' },
  },
  {
    path: 'settings',
    navLabel: 'Settings',
    kind: 'settings',
    eyebrow: 'Administration',
    title: 'Settings',
    description: 'Open the site, content, and publishing tools that configure the workspace.',
    primaryAction: { label: 'Manage sites', path: '/sites' },
  },
  {
    path: 'sites',
    navLabel: 'Sites',
    kind: 'sites',
    eyebrow: 'Tenancy',
    title: 'Sites',
    description: 'Create and switch between multiple sites, each with its own config.',
    primaryAction: { label: 'Open site settings', path: '/site-settings' },
  },
  {
    path: 'site-settings',
    navLabel: 'Site Settings',
    kind: 'site-settings',
    eyebrow: 'Configuration',
    title: 'Site Settings',
    description: 'Update domain, blog path, template, storage, AI, and deployment config.',
    primaryAction: { label: 'Save settings', path: '/sites' },
  },
  {
    path: 'landing-page-editor',
    navLabel: 'Landing Page Editor',
    kind: 'landing-page-editor',
    eyebrow: 'Content design',
    title: 'Landing Page Editor',
    description: 'Manage sections, toggle visibility, and reorder the selected site landing page.',
    primaryAction: { label: 'Edit articles', path: '/articles' },
  },
  {
    path: 'articles',
    navLabel: 'Articles',
    kind: 'articles',
    eyebrow: 'Editorial',
    title: 'Articles',
    description: 'Review drafts, publish content, and track the editorial workflow.',
    primaryAction: { label: 'Open editor', path: '/article-editor' },
  },
  {
    path: 'article-editor',
    navLabel: 'Article Editor',
    kind: 'article-editor',
    eyebrow: 'Writing',
    title: 'Article Editor',
    description: 'Draft, review, and publish an article with SEO and AI metadata.',
    primaryAction: { label: 'Save draft', path: '/articles' },
  },
  {
    path: 'authors',
    navLabel: 'Authors',
    kind: 'authors',
    eyebrow: 'People',
    title: 'Authors',
    description: 'Manage contributor profiles and ownership for published articles.',
    primaryAction: { label: 'Review articles', path: '/articles' },
  },
  {
    path: 'categories',
    navLabel: 'Categories',
    kind: 'categories',
    eyebrow: 'Taxonomy',
    title: 'Categories',
    description: 'Keep editorial categories consistent and easy to navigate.',
    primaryAction: { label: 'Open tags', path: '/tags' },
  },
  {
    path: 'tags',
    navLabel: 'Tags',
    kind: 'tags',
    eyebrow: 'Labels',
    title: 'Tags',
    description: 'Use reusable tags to connect content across campaigns and topics.',
    primaryAction: { label: 'Open media library', path: '/media-library' },
  },
  {
    path: 'media-library',
    navLabel: 'Media Library',
    kind: 'media-library',
    eyebrow: 'Assets',
    title: 'Media Library',
    description: 'Upload and organize site assets for articles and landing pages.',
    primaryAction: { label: 'Add media', path: '/media-library' },
  },
  {
    path: 'ai-assistant',
    navLabel: 'AI Assistant',
    kind: 'ai-assistant',
    eyebrow: 'Assistive writing',
    title: 'AI Assistant',
    description: 'Generate drafts and ideas without ever auto-publishing content.',
    primaryAction: { label: 'Open article editor', path: '/article-editor' },
  },
  {
    path: 'builds',
    navLabel: 'Builds',
    kind: 'builds',
    eyebrow: 'Delivery',
    title: 'Builds',
    description: 'Track preview and published builds for the selected site.',
    primaryAction: { label: 'Trigger build', path: '/builds' },
  },
  {
    path: 'deployment-settings',
    navLabel: 'Deployment Settings',
    kind: 'deployment-settings',
    eyebrow: 'Publishing',
    title: 'Deployment Settings',
    description: 'Configure where the builder deploys each site and how secrets are referenced.',
    primaryAction: { label: 'Open builds', path: '/builds' },
  },
];
